.TH "K4DIRSTAT" "1" "Mai 2015" "" ""
.
.SH "NOM"
\fBk4dirstat\fR \- Statistiques graphiques des répertoires
.
.SH "SYNOPSIS"
\fBk4dirstat\fR [\fIOPTIONS\fR\.\.\.] [\fIchemin ou url\fR]
.
.SH "DESCRIPTION"
Affiche où est passé tout votre espace disque et vous aide à le nettoyer\. La taille des fichiers et des répertoires est affichée sous forme de carte d'arborescence\.
.
.TP
\fIchemin ou url\fR
Répertoire ou URL à ouvrir
.
.SH "OPTIONS"
.
.TP
\fB\-v\fR, \fB\-version\fR
Affiche les informations de version et quitte\.
.
.SS "Options Qt"
.
.TP
\fB\-platform\fR \fInomPlateforme[:options]\fR
spécifie le module Qt Platform Abstraction (QPA)\. Remplacé par la variable d'environnement \fBQT_QPA_PLATFORM\fR\.
.
.TP
\fB\-platformpluginpath\fR \fIchemin\fR
spécifie le chemin vers les modules de plateforme\. Remplacé par la variable d'environnement \fBQT_QPA_PLATFORM_PLUGIN_PATH\fR\.
.
.TP
\fB\-platformtheme\fR \fIthèmePlateforme\fR
spécifie le thème de la plateforme\. Remplacé par la variable d'environnement \fBQT_QPA_PLATFORMTHEME\fR\.
.
.TP
\fB\-plugin\fR \fImodule\fR
spécifie des modules supplémentaires à charger\. L'argument peut apparaître plusieurs fois\. Remplacé par la variable d'environnement \fBQT_QPA_GENERIC_PLUGINS\fR\.
.
.TP
\fB\-qwindowgeometry\fR \fIgéométrie\fR
spécifie la géométrie de la fenêtre principale en syntaxe X11\. Par exemple : \fB\-qwindowgeometry 100x100+50+50\fR\.
.
.TP
\fB\-qwindowicon\fR
définit l'icône de fenêtre par défaut\.
.
.TP
\fB\-qwindowtitle\fR
définit le titre de la première fenêtre\.
.
.TP
\fB\-display\fR \fIhôte\fR
numéro_écran, change d'écran sous X11\. Remplace la variable d'environnement \fBDISPLAY\fR\.
.
.TP
\fB\-geometry\fR
géométrie, identique à \fB\-qwindowgeometry\fR\.
.
.SH "AUTEUR"
Cette page de manuel a été rédigée par Jerome Robert\.
